tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/cask-fonts"

# Import host specific dependencies
eval(File.read(
    "#{ENV["HOMEBREW_BUNDLE_DIR"]}/#{`hostname -s`.strip.downcase}-brewfile.rb"
))

#### TERMINAL SETUP DEPENDENCIES
brew "bat"                          # cat but with formatting
brew "fd"                           # find alternative
cask "font-jetbrains-mono-nerd-font"# nerd font
brew "fzf"                          # Fuzzy finder
cask "iterm2"                       # iterm2 terminal emulator
brew "lsd"                          # Clone of ls with colorful output, file type icons, and more
brew "navi"                         # Interactive cheatsheet tool
brew "starship"                     # Starship prompt

#### OTHER TERMINAL UTILS
brew "bottom"                       # alternative to htop
brew "broot"                        # New way to see and navigate directory trees
brew "curl"                         # curl - installing for the completions which are missing from macos
brew "ffmpeg"                       # Play, record, convert, and stream audio and video
brew "gum"                          # Tool for creating interactive scripts
brew "htop"                         # Realtime info on running processes
brew "jq"                           # Json processor
brew "socat"                        # Socket CAT: netcat on steroids
brew "websocat"                     # CLI for WebSockets

#### DEVELOPMENT TOOLS / APPS
cask "drawio"                       # drawio app
brew "fnm"                          # faster nvm
brew "git"                          # Git
brew "poetry"                       # Dependancy management for Python
cask "visual-studio-code"           # vscode
