tap "nats-io/nats-tools"

cask "1password"
brew "ansible"
brew "awscli"
cask "docker"
# cask "firefox"
cask "microsoft-edge"
cask "microsoft-teams"
brew "nats"
brew "nomad"
brew "packer"
cask "rectangle"
brew "terraform"
