tap "nats-io/nats-tools"

cask "1password"
brew "ansible"
brew "awscli"
cask "docker"
# cask "firefox"
cask "iina"
cask "microsoft-edge"
cask "microsoft-teams"
brew "nats"
brew "nomad"
cask "rectangle"
cask "shottr"
brew "terraform"
