#!/usr/bin/env bash

alias cat='bat --paging=never --style="numbers"'

alias ls='exa --icons'          # ls
alias ll='ls -lbF --git'        # long list
alias la='ll -lbFa --git'       # all list
alias lt='la --tree --level=2'  # tree view

alias path='echo $PATH | tr -s ":" "\n"'
alias fpath='echo $FPATH | tr -s ":" "\n"'

alias sshk='kitty +kitten ssh'          # install kitty-terminfo manually with `$ ssh-kitty-terminfo user@remote` if seeing messages like "WARNING: terminal is not fully functional" or "'xterm-kitty': unknown terminal type"
alias ssht='ssh -f -N -D 9090'          # Open SOCKS5 SSH Tunnel in background 127.0.0.1:9090

alias lowercase="tr '[:upper:]' '[:lower:]'"
alias uppercase="tr '[:lower:]' '[:upper:]'"

alias map='xargs -n1'   # Intuitive map function (eg. `$ find . -name .gitattributes | map dirname`)

alias watch='~/dev/gist-watch/watch'

alias open-cheatsheet='cat ~/dotfiles/cheatsheet.md'
alias open-hoppscotch='open https://hoppscotch.io/'      # Open Postman alternative
