#!/usr/bin/env bash

alias cat='bat --paging=never --style="numbers"'

alias ls='exa --icons'          # ls
alias ll='ls -lbF --git'        # long list
alias la='ll -lbFa --git'       # all list
alias lt='la --tree --level=2'  # tree view

alias path='echo $PATH | tr -s ":" "\n"'
alias fpath='echo $FPATH | tr -s ":" "\n"'

[ "$TERM" = "xterm-kitty" ] && alias ssh="kitty +kitten ssh"    # use the kitty ssh which will automatically setup the kitty-terminfo if in kitty (related: ssh-kitty-terminfo in functions)
alias ssht='ssh -f -N -D 9090'                                  # Open SOCKS5 SSH Tunnel in background 127.0.0.1:9090

alias lowercase="tr '[:upper:]' '[:lower:]'"
alias uppercase="tr '[:lower:]' '[:upper:]'"

alias map='xargs -n1'   # Intuitive map function (eg. `$ find . -name .gitattributes | map dirname`)

alias watch='~/dev/gist-watch/watch'

alias open-cheatsheet='cat ~/dotfiles/cheatsheet.md'
alias open-hoppscotch='open https://hoppscotch.io/'      # Open Postman alternative
