#!/usr/bin/env bash

alias cat='bat --paging=never --style="numbers"'

alias ls='lsd'
alias ll='ls -l'
alias la='ls -la'
alias lt='ls --tree --depth 2'

alias dua='br -w'               # dua alternatove using broot

alias path='echo $PATH | tr -s ":" "\n"'
alias fpath='echo $FPATH | tr -s ":" "\n"'

[ "$TERM" = "xterm-kitty" ] && alias ssh="kitty +kitten ssh"    # use the kitty ssh which will automatically setup the kitty-terminfo if in kitty (related: ssh-kitty-terminfo in functions)
alias ssht='ssh -f -N -D 9090'                                  # Open SOCKS5 SSH Tunnel in background 127.0.0.1:9090

alias lowercase="tr '[:upper:]' '[:lower:]'"
alias uppercase="tr '[:lower:]' '[:upper:]'"

alias git-changes-choose='git status --short | cut -c 4- | gum choose'
alias git-branch-choose='git branch | cut -c 3- | gum choose'
alias git-stage='git-changes-choose --no-limit | xargs git add'
alias git-unstage='git-changes-choose --no-limit | xargs git reset --'
alias git-restore='git-changes-choose --no-limit | xargs git restore'
alias git-branch-delete='git-branch-choose --no-limit | xargs git branch -D'
alias git-branch-parent='git show-branch | sed "s/].*//" | grep "\*" | grep -v "$(git rev-parse --abbrev-ref HEAD)" | head -n1 | sed "s/^.*\[//"'

alias watch='~/dev/gist-watch/watch'

alias open-cheatsheet='cat ~/dotfiles/cheatsheet.md'
alias open-hoppscotch='open https://hoppscotch.io/'      # Open Postman alternative
