# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = '${custom.iterm2_mark}$all'

[character]
success_symbol = '[ ↳]()'
error_symbol = '[ ↳](red)'

# [line_break]
# disabled = true

[cmd_duration]
disabled = true # using the zsh timer instead

[directory]
read_only = " "

[git_branch]
symbol = " "

[hostname]
ssh_only = true
format = '[\[$hostname\]]($style) ' # Looks better without the symbol

[nix_shell]
format = 'via [$name]($style) ' # Removed symbol and state (impure / pure)

[package]
disabled = true # Package version is rarely useful

[rust]
format = 'via [$symbol($version \($toolchain\) )]($style)'

[terraform]
disabled = true # Don't really care about the terraform workspace

# iterm2 shell integration adds marks to the start of each prompt, however,
# if we have new_line enabled in starship this is added prior to the new line
# so this command adds it in explicitly instead
#  - requires `export ITERM2_SQUELCH_MARK=1` to disable the automatic iterm2 shell integration marks
#  - requires `${custom.iterm2_mark}` to be added to the start of the starship format
[custom.iterm2_mark]
command = 'printf "\033]133;A\007"' # iterm2_prompt_mark
when = ''' test "$LC_TERMINAL" = "iTerm2" '''
