#!/usr/bin/env bash

# Easier navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# ls aliases
alias l="ls -lFh --color"                              # List all files colorized in long format
alias la="ls -lAFh --color"                            # List all files colorized in long format, excluding . and ..
alias lsd="ls -lFh --color | grep --color=never '^d'"  # List only directories
alias ls="command ls --color"                         # Always use color output for `ls`

# Run git status on all of the subdirectories in the dev directory
alias gsdev="find ~/dev -maxdepth 1 -mindepth 1 -type d -exec sh -c '(echo {} && cd {} && git status -s && echo)' \;"

# Pretty print the path
alias path='echo $PATH | tr -s ":" "\n"'

alias publicip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ifconfig | grep -E \"([0-9]{1,3}\.){3}[0-9]{1,3}\" | grep -v 127.0.0.1 | awk '{ print }' | cut -f2 -d:"

# Intuitive map function
# For example, to list all directories that contain a certain file:
# find . -name .gitattributes | map dirname
alias map="xargs -n1"
