#!/usr/bin/env bash

# Bat is a nicer version of cat with matching api
alias cat='bat --paging=never'

alias ls='exa'                          # ls
alias ll='exa -lbF --git'               # long list
alias la='exa -lbFa --git'              # all list
alias lt='exa --tree --level=2'         # tree view

# Run git status on all of the subdirectories in the dev directory
alias gsdev="find ~/dev -maxdepth 1 -mindepth 1 -type d -exec sh -c '(echo {} && cd {} && git status -s && echo)' \;"

# Pretty print the path
alias path='echo $PATH | tr -s ":" "\n"'

# Intuitive map function
# For example, to list all directories that contain a certain file:
# find . -name .gitattributes | map dirname
alias map="xargs -n1"
