#!/usr/bin/env bash

# Create a new directory and enter it
function mkd() {
	mkdir -p "$@" && cd "$_" || exit;
}

# Use bat to format help output
function help() {
    "$@" --help 2>&1 | bat --plain --language=help --paging=never
}

# Create a data URL from a file
function dataurl() {
	local mimeType;
	mimeType=$(file -b --mime-type "$1");
	if [[ $mimeType == text/* ]]; then
		mimeType="${mimeType};charset=utf-8";
	fi
	echo "data:${mimeType};base64,$(openssl base64 -in "$1" | tr -d '\n')";
}

function localip() {
	ifconfig en0 | grep inet | awk '$1=="inet" {print $2}';
}

function publicip() {
	echo "Public IPv4: $( publicipv4 )";
	echo "Public IPv6: $( publicipv6 )";
}

function publicipv4() {
	dig -4 TXT +short o-o.myaddr.l.google.com @ns1.google.com;
}

function publicipv6() {
	dig -6 TXT +short o-o.myaddr.l.google.com @ns1.google.com;
}
