# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && . "$HOME/.fig/shell/zshrc.pre.zsh"

export ZSH="$HOME/.oh-my-zsh"
plugins=(dotenv encode64 extract timer urltools zsh-autosuggestions zsh-syntax-highlighting)

# Add system binaries to the path
export PATH=/sbin:$PATH

# Use bat to format man page output
export MANPAGER="sh -c 'col -bx | bat -l man -p --paging=never'"

eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(starship init zsh)"
eval "$(fnm env --use-on-cd)"
eval "$(direnv hook zsh)"
eval "$(conda shell.zsh hook)"

source $HOME/.cargo/env
source $HOME/.aliases
source $HOME/.functions
source $ZSH/oh-my-zsh.sh

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && . "$HOME/.fig/shell/zshrc.post.zsh"
