export PATH=/sbin:$PATH

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME=""
plugins=(git)

eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(starship init zsh)"
eval "$(fnm env --use-on-cd)"

source ~/.aliases
source ~/.functions

source $ZSH/oh-my-zsh.sh
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
